name: Reusable CI

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.12"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install (best-effort)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install .; fi

      - name: Lint (ruff if available)
        run: |
          if python -c "import importlib; import sys; sys.exit(0 if importlib.util.find_spec('ruff') else 1)"; then
            ruff check .
          else
            echo "ruff not installed; skipping"
          fi

      - name: Tests (pytest if available)
        run: |
          if python -c "import importlib; import sys; sys.exit(0 if importlib.util.find_spec('pytest') else 1)"; then
            pytest -q
          else
            echo "pytest not installed; skipping"
          fi
